config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  resources :meals

  devise_for :users

  post "/cart/finish" => "cart#finish"
  post "/cart/:id" => "cart#add"
  get "/buys" => "cart#buys"

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	belongs_to :user

	scope :bought, -> { where(buy: true) }

	has_many :products

	def add(meal)
		Product.create(cart_id: self.id, meal_id: meal.id)
	end

	def finish(user_id)
		update({buy: true, user_id: user_id, buy_date: Date.today})
	end

end

app/models/meal.rb
class Meal < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :meal
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :total_cart, :is_admin?

  def is_admin?
  	user = current_user || User.new
  	user.admin 
  end

  def my_cart
  	cart = Cart.find(session[:cart_id]) unless session[:cart_id].nil?
  	if (cart.nil?)
  		cart = Cart.create
  		session[:cart_id] = cart.id
  	end
  	cart
  end

  def total_cart
  	total = 0
  	my_cart.products.each do |product|
  		total += product.meal.value
  	end
  	total
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
	before_action :verify_user, only: [:finish]
	before_action :verify_admin, only: [:buys]
	skip_before_filter :verify_authenticity_token, :only => [:add, :finish]

	def add
		meal = Meal.find(params[:id])
		my_cart.add(meal)
		redirect_to "/"
	end

	def finish
		my_cart.finish(current_user.id)
		session[:cart_id] = Cart.create.id
		redirect_to "/"
	end

	def buys
		@carts = Cart.bought
	end

	private
		def verify_user
	    redirect_to "/users/sign_up" if current_user.nil?
	  end
		def verify_admin
	    redirect_to "/" unless is_admin?
	  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@meals = Meal.all
	end

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :verify_admin
  before_action :set_meal, only: [:show, :edit, :update, :destroy]

  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.all
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
  end

  # GET /meals/new
  def new
    @meal = Meal.new
  end

  # GET /meals/1/edit
  def edit
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(meal_params)

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Meal was successfully created.' }
        format.json { render :show, status: :created, location: @meal }
      else
        format.html { render :new }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    respond_to do |format|
      if @meal.update(meal_params)
        format.html { redirect_to @meal, notice: 'Meal was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal }
      else
        format.html { render :edit }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to meals_url, notice: 'Meal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal
      @meal = Meal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_params
      params.require(:meal).permit(:name, :description, :value, :image)
    end

    def verify_admin
      redirect_to "/" unless is_admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/cart/buys.html.erb
<table >
	<thead>
		<tr>
			<th>Usuário</th>
			<th>Data</th>
		</tr>
	</thead>
	<tbody>
		<% @carts.each do |cart| %>
			<tr>
				<td><%= cart.user.email %></td>
				<td><%= cart.buy_date %></td>
				<table border="1">
					<thead>
						<tr>
							<th>Produto</th>
							<th>Valor</th>
						</tr>
					</thead>
					<tbody>
						<% cart.products.each do |product| %>
							<tr>
								<td> <%= product.meal.name %> </td>
								<td> <%= product.meal.value %> </td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/home/index.html.erb
<h4>Escolha sua refeição</h4>

<table>
	<thead>
		<tr>
			<th>Nome</th>
			<th>Descrição</th>
			<th>Valor</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @meals.each do |meal| %>
			<tr>
				<td><%= meal.name %></td>
				<td><%= meal.description %></td>
				<td><%= meal.value %></td>
				<td><img src="<%= meal.image.url %>" width="256" height="256"></td>
				<td>
					<form action="/cart/<%= meal.id %>" method="POST">
						<button type="submit">Adicionar ao carrinho</button>
					</form>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyMeal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<ul>
		<li><a href="/">Início</a></li>
		<% if is_admin? %>
			<li><a href="/meals">Cadastrar Refeição</a></li>
			<li><a href="/buys">Compras</a></li>
		<% end %>
		<li>
			Total do Carrinho: <%= total_cart %> 
			<form action="/cart/finish" method="POST">
				<button type="submit">Finalizar</button>
			</form>
		</li>
		<% if current_user.nil? %>
			<li><a href="/users/sign_in">Entrar</a></li>
			<li><a href="/users/sign_up">Cadastrar</a></li>
		<% end %>
		<% if !current_user.nil? %>
			<li><a href="/users/sign_out">Sair</a></li>
		<% end %>
	</ul>
	<%= yield %>

</body>
</html>

app/views/meals/_form.html.erb
<%= form_for(@meal, multipart: true) do |f| %>
  <% if @meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% @meal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meals/edit.html.erb
<h1>Editing Meal</h1>

<%= render 'form' %>

<%= link_to 'Show', @meal %> |
<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Meals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meals.each do |meal| %>
      <tr>
        <td><%= meal.name %></td>
        <td><%= meal.description %></td>
        <td><%= meal.value %></td>
        <td><%= link_to 'Show', meal %></td>
        <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
        <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meal', new_meal_path %>

app/views/meals/new.html.erb
<h1>New Meal</h1>

<%= render 'form' %>

<%= link_to 'Back', meals_path %>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meal.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @meal.description %>
</p>

<p>
  <strong>Value:</strong>
  <%= @meal.value %>
</p>

<%= link_to 'Edit', edit_meal_path(@meal) %> |
<%= link_to 'Back', meals_path %>